kb2(acute_cough,               [b960_mycoplasma_pneumoniae],                                                   ['Mycoplasmal bronchitis or pneumonia'],          [],                                        [lasting_less_than_3_weeks,posttussive_emesis,inspiratory_whoop,paroxysmal_cough,abnormal_chest_film],                                                                                                                                                                                                                            [],[],[]                                                                                                                                     ,[],[],[]).
kb2(acute_cough,               [j09_j18_10_influenza_and_pneumonia],                                           ['Bacterial pneumonia'],                          [],                                        [lasting_less_than_3_weeks,tachycardia,tachypnea,fever,rales,decreased_breath_sounds,fremitus,egophony],                                                                                                                                                                                                                           [],[],[]                                                                                                                                    ,[],[],[]).
kb2(acute_cough,               [j20_acute_bronchitis],                                                         ['Viral bronchitis'],                             [],                                        [lasting_less_than_3_weeks,wheezing,rhonchi],                                                                                                                                                                                                                                                                                      [],[],[]                                                                                                                                    ,[],[],[]).
kb2(chronic_or_recurrent_cough,[icd10codemissing],                                                             ['Postnasal_drip'],                               [],                                        [lasting_more_than_3_weeks,angiotensin_converting_enzyme_ACE_is_absent,inhibitor_therapy_is_absent,acute_respiratory_tract_infection_is_absent,chest_radiograph_abnormalities_are_absent,nasal_congestion,sinus_congestion,wheezing,heartburn],                                                                                    [],[],[]                                                                                                                                    ,[],[],[]).
kb2(chronic_or_recurrent_cough,[j45_asthma],                                                                   ['Asthma'],                                       [],                                        [lasting_more_than_3_weeks,angiotensin_converting_enzyme_ACE_is_absent,inhibitor_therapy_is_absent,acute_respiratory_tract_infection_is_absent,chest_radiograph_abnormalities_are_absent,nasal_congestion,sinus_congestion,wheezing,heartburn,increased_eosinophil_counts_to_induced_sputum,increased_exhaled_nitric_oxide_levels],[],[],[providing_an_empiric_trial_of_prednisone_30_mg_daily_for_2_weeks]                                                                    ,[],[],[]).
kb2(chronic_or_recurrent_cough,[j44_other_chronic_obstructive_pulmonary_disease],                              ['Chronic obstructive pulmonary disease'],        [patients_more_than_50_years_of_age],      [lasting_more_than_3_weeks,excessive_mucus_secretions,purulent_sputum,patients_more_than_50_years_of_age,nocturnal_cough,persistent_cough_with_phlegm],                                                                                                                                                                            [],[],[]                                                                                                                                    ,[],[],[]).
kb2(chronic_or_recurrent_cough,[k21_gastro_oesophageal_reflux_disease],                                        ['Gastroesophageal reflux'],                      [],                                        [lasting_more_than_3_weeks,angiotensin_converting_enzyme_ACE_is_absent,inhibitor_therapy_is_absent,acute_respiratory_tract_infection_is_absent,chest_radiograph_abnormalities_are_absent,nasal_congestion,sinus_congestion,wheezing,heartburn],                                                                                    [],[],[]                                                                                                                                    ,[],[],[]).
kb2(chronic_or_recurrent_cough,[c34_90_malignant_neoplasm_of_unspecified_part_of_unspecified_bronchus_or_lung],['Bronchogenic carcinoma'],                       [],                                        [lasting_more_than_3_weeks,unexplained_weight_loss,unexplained_fevers_with_night_sweats,significant_tobacco_exposures,occupational_exposures],                                                                                                                                                                                     [],[],[]                                                                                                                                    ,[],[],[]).


kb2(abdominal_pain, [], [], [], [], [], [], [], [], [], []).
kb2(chest_pain, [], [], [], [], [], [], [], [], [], []).
